### ISSUE TITLE
implement catalogue statistics against WCMP quality assessment metrics

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/pywiscat#4]
Implement various statistics atop the WIS catalogue per https://github.com/wmo-im/wcmp/issues/51.  Possible metrics (overall, or grouped by GISC/country/citation authority):

- [ ] KPI
- [ ] ATS (or not, given KPI-1 is the ATS itself)
- [ ] Scoring rubric

We can integrate [pywcmp](https://github.com/wmo-im/pywcmp) for the baseline functionality and pywiscat will basically do the accounting/statistics.

**Comment by amilan17** [comment]
@tomkralidis @josusky Is there a way to run the KPI metrics now locally on a set of records?

**Comment by josusky** [comment]
Running `pywcmp` from `pywiscat` to test a list of metadata files (folder) at once is not a big technical issue. But what should be the result of such analysis? The simplest is to just put outputs of individual `pywcmp` runs together into one "dictionary" (that will be printed out as JSON). Here comes my first question:
* Should the key in this dictionary be the file name (path) or the file identifier, in other words "tests/data/urn_x-wmo_md_int.ecmwf__HRXG00ECMF.xml" or "urn:x-wmo:md:int.ecmwf::HRXG00ECMF"?

I suppose that we would like to have also some form of simpler output. Of course, we can instruct `pywcmp` to print only the "summary" section. Here comes the second question:
* Is this brief enough or should we add an extra brief summary, e.g. just percentage and grade for each file?

When it concerns the additional grouping, could you be more specific? 
* citation authority - in the file identifier?
* GISC - I am afraid that from a metadata record itself we do not know the GISC under whose responsibility it belongs ... It is probably easier to have records from different GISC in different folders, thus to do this kind of grouping externally.
* country - from the citation authority / file identifier or from originator / point of contact?

**Comment by josusky** [comment]
Example of possible usage:
`pywiscat wis1 report kpi -f tests/data/small_list.json -o brief`
Output:
```
{
    "tests/data/de.dkrz.wdcc.iso2000013.xml": {
        "percentage": 48.529,
        "grade": "U",
        "identifier": "de.dkrz.wdcc.iso2000013"
    }
}
```

**Comment by tomkralidis** [comment]
Implemented by @josusky, to demo at next TT-WISMD meeting.
